import 'package:crm/dynamic_dashboard/models/dashboard_models.dart';
import 'package:crm/dynamic_dashboard/registry/dashboard_widget_registry.dart';
import 'package:flutter/material.dart';

DashboardConfig buildDefaultDashboardConfig({
  required String dashboardKey,
  required DashboardWidgetRegistry registry,
}) {
  switch (dashboardKey) {
    case 'association_dashboard':
      return _buildAssociationDashboardDefaultConfig(
        dashboardKey: dashboardKey,
        registry: registry,
      );

    case 'client_panel_dashboard':
      return _buildClientPanelDashboardConfig(
        dashboardKey: dashboardKey,
        registry: registry,
      );

      case 'crm_user_panel_dashboard':
      return _buildCrmUserPanelDashboardConfig(
        dashboardKey: dashboardKey,
        registry: registry,
      );

    case 'crm_main':
    case 'agent_dashboard':
    case 'office_owner_dashboard':
      return _buildCrmDefaultDashboardConfig(
        dashboardKey: dashboardKey,
        registry: registry,
      );

    default:
      return _buildCrmDefaultDashboardConfig(
        dashboardKey: dashboardKey,
        registry: registry,
      );
  }
}

DashboardLayoutItem _item(
  DashboardWidgetRegistry registry,
  String instanceId,
  String type,
  DashboardBreakpoint breakpoint, {
  required int x,
  required int y,
  int? w,
  int? h,
}) {
  final spec = registry.byType(type);

  if (spec == null) {
    throw FlutterError(
      'Dashboard widget type "$type" is not registered. '
      'Check DashboardWidgetRegistry and dashboard catalog backfill.',
    );
  }

  final size = spec.defaultSize(breakpoint);

  return DashboardLayoutItem(
    instanceId: instanceId,
    x: x,
    y: y,
    w: w ?? size.w,
    h: h ?? size.h,
  );
}

DashboardConfig _buildCrmDefaultDashboardConfig({
  required String dashboardKey,
  required DashboardWidgetRegistry registry,
}) {
  const instances = [
    DashboardWidgetInstance(
      id: 'welcome_header_1',
      type: 'welcome_header',
    ),
    DashboardWidgetInstance(
      id: 'market_overview_1',
      type: 'market_overview',
    ),
    DashboardWidgetInstance(
      id: 'last_month_stats_1',
      type: 'last_month_stats',
    ),
    DashboardWidgetInstance(
      id: 'calendar_1',
      type: 'calendar',
    ),
    DashboardWidgetInstance(
      id: 'recent_leads_1',
      type: 'recent_leads',
    ),
    DashboardWidgetInstance(
      id: 'favorite_ads_1',
      type: 'favorite_ads',
    ),
    DashboardWidgetInstance(
      id: 'financial_1',
      type: 'financial',
    ),
    DashboardWidgetInstance(
      id: 'earnings_chart_1',
      type: 'earnings_chart',
    ),
  ];

  return DashboardConfig(
    dashboardKey: dashboardKey,
    revision: 1,
    updatedAt: null,
    instances: instances,
    layouts: {
      DashboardBreakpoint.desktop: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.desktop,
        columns: 12,
        rowHeight: 110,
        gap: 20,
        canvasPadding: 10,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'welcome_header_1',
            'welcome_header',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 0,
            w: 12,
            h: 1,
          ),
          _item(
            registry,
            'market_overview_1',
            'market_overview',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 1,
            w: 12,
            h: 2,
          ),
          _item(
            registry,
            'last_month_stats_1',
            'last_month_stats',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 3,
            w: 3,
            h: 2,
          ),
          _item(
            registry,
            'financial_1',
            'financial',
            DashboardBreakpoint.desktop,
            x: 3,
            y: 3,
            w: 5,
            h: 5,
          ),
          _item(
            registry,
            'calendar_1',
            'calendar',
            DashboardBreakpoint.desktop,
            x: 8,
            y: 3,
            w: 4,
            h: 7,
          ),
          _item(
            registry,
            'recent_leads_1',
            'recent_leads',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 5,
            w: 3,
            h: 3,
          ),
          _item(
            registry,
            'earnings_chart_1',
            'earnings_chart',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 8,
            w: 8,
            h: 4,
          ),
          _item(
            registry,
            'favorite_ads_1',
            'favorite_ads',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 12,
            w: 12,
            h: 4,
          ),
        ],
      ),
      DashboardBreakpoint.tablet: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.tablet,
        columns: 8,
        rowHeight: 100,
        gap: 16,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'welcome_header_1',
            'welcome_header',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 0,
            w: 8,
            h: 1,
          ),
          _item(
            registry,
            'market_overview_1',
            'market_overview',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 1,
            w: 8,
            h: 2,
          ),
          _item(
            registry,
            'last_month_stats_1',
            'last_month_stats',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 3,
            w: 3,
            h: 2,
          ),
          _item(
            registry,
            'financial_1',
            'financial',
            DashboardBreakpoint.tablet,
            x: 3,
            y: 3,
            w: 5,
            h: 4,
          ),
          _item(
            registry,
            'calendar_1',
            'calendar',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 5,
            w: 3,
            h: 7,
          ),
          _item(
            registry,
            'recent_leads_1',
            'recent_leads',
            DashboardBreakpoint.tablet,
            x: 3,
            y: 7,
            w: 5,
            h: 4,
          ),
          _item(
            registry,
            'earnings_chart_1',
            'earnings_chart',
            DashboardBreakpoint.tablet,
            x: 3,
            y: 11,
            w: 5,
            h: 4,
          ),
          _item(
            registry,
            'favorite_ads_1',
            'favorite_ads',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 12,
            w: 3,
            h: 4,
          ),
        ],
      ),
      DashboardBreakpoint.mobile: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.mobile,
        columns: 4,
        rowHeight: 92,
        gap: 12,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'welcome_header_1',
            'welcome_header',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 0,
            w: 4,
            h: 1,
          ),
          _item(
            registry,
            'last_month_stats_1',
            'last_month_stats',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 1,
            w: 4,
            h: 3,
          ),
          _item(
            registry,
            'financial_1',
            'financial',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 4,
            w: 4,
            h: 3,
          ),
          _item(
            registry,
            'calendar_1',
            'calendar',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 7,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'recent_leads_1',
            'recent_leads',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 12,
            w: 4,
            h: 4,
          ),
          _item(
            registry,
            'earnings_chart_1',
            'earnings_chart',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 16,
            w: 4,
            h: 4,
          ),
          _item(
            registry,
            'favorite_ads_1',
            'favorite_ads',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 20,
            w: 4,
            h: 4,
          ),
        ],
      ),
    },
  );
}

DashboardConfig _buildAssociationDashboardDefaultConfig({
  required String dashboardKey,
  required DashboardWidgetRegistry registry,
}) {
  const instances = [
    DashboardWidgetInstance(
      id: 'association_welcome_header_1',
      type: 'association_welcome_header',
    ),
    DashboardWidgetInstance(
      id: 'association_overview_1',
      type: 'association_overview',
      settings: {
        'days': 30,
      },
    ),
    DashboardWidgetInstance(
      id: 'association_loyalty_1',
      type: 'association_loyalty',
      settings: {
        'programId': 1,
      },
    ),
    DashboardWidgetInstance(
      id: 'association_announcements_1',
      type: 'association_announcements',
    ),
    DashboardWidgetInstance(
      id: 'association_membership_status_1',
      type: 'association_membership_status',
    ),
    DashboardWidgetInstance(
      id: 'calendar_1',
      type: 'calendar',
    ),
  ];

  return DashboardConfig(
    dashboardKey: dashboardKey,
    revision: 1,
    updatedAt: null,
    instances: instances,
    layouts: {
      DashboardBreakpoint.desktop: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.desktop,
        columns: 12,
        rowHeight: 110,
        gap: 20,
        canvasPadding: 10,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'association_welcome_header_1',
            'association_welcome_header',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 0,
            w: 12,
            h: 1,
          ),
          _item(
            registry,
            'association_overview_1',
            'association_overview',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 1,
            w: 8,
            h: 2,
          ),
          _item(
            registry,
            'association_loyalty_1',
            'association_loyalty',
            DashboardBreakpoint.desktop,
            x: 8,
            y: 1,
            w: 4,
            h: 1,
          ),
          _item(
            registry,
            'calendar_1',
            'calendar',
            DashboardBreakpoint.desktop,
            x: 8,
            y: 2,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'association_announcements_1',
            'association_announcements',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 3,
            w: 4,
            h: 4,
          ),
          _item(
            registry,
            'association_membership_status_1',
            'association_membership_status',
            DashboardBreakpoint.desktop,
            x: 4,
            y: 3,
            w: 4,
            h: 4,
          ),
        ],
      ),
      DashboardBreakpoint.tablet: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.tablet,
        columns: 8,
        rowHeight: 100,
        gap: 16,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'association_welcome_header_1',
            'association_welcome_header',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 0,
            w: 8,
            h: 1,
          ),
          _item(
            registry,
            'association_overview_1',
            'association_overview',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 1,
            w: 8,
            h: 2,
          ),
          _item(
            registry,
            'association_loyalty_1',
            'association_loyalty',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 3,
            w: 4,
            h: 1,
          ),
          _item(
            registry,
            'calendar_1',
            'calendar',
            DashboardBreakpoint.tablet,
            x: 4,
            y: 3,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'association_announcements_1',
            'association_announcements',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 4,
            w: 4,
            h: 4,
          ),
          _item(
            registry,
            'association_membership_status_1',
            'association_membership_status',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 8,
            w: 8,
            h: 4,
          ),
        ],
      ),
      DashboardBreakpoint.mobile: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.mobile,
        columns: 4,
        rowHeight: 92,
        gap: 12,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'association_welcome_header_1',
            'association_welcome_header',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 0,
            w: 4,
            h: 1,
          ),
          _item(
            registry,
            'association_loyalty_1',
            'association_loyalty',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 1,
            w: 4,
            h: 1,
          ),
          _item(
            registry,
            'association_overview_1',
            'association_overview',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 2,
            w: 4,
            h: 2,
          ),
          _item(
            registry,
            'calendar_1',
            'calendar',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 4,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'association_announcements_1',
            'association_announcements',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 9,
            w: 4,
            h: 4,
          ),
          _item(
            registry,
            'association_membership_status_1',
            'association_membership_status',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 13,
            w: 4,
            h: 5,
          ),
        ],
      ),
    },
  );
}

DashboardConfig _buildClientPanelDashboardConfig({
  required String dashboardKey,
  required DashboardWidgetRegistry registry,
}) {
  const instances = [
    DashboardWidgetInstance(
      id: 'client_profile_1',
      type: 'client_profile',
    ),
    DashboardWidgetInstance(
      id: 'client_details_1',
      type: 'client_details',
    ),
    DashboardWidgetInstance(
      id: 'client_events_1',
      type: 'client_events',
    ),
    DashboardWidgetInstance(
      id: 'client_transactions_1',
      type: 'client_transactions',
    ),
    DashboardWidgetInstance(
      id: 'client_todo_1',
      type: 'client_todo',
    ),
  ];

  return DashboardConfig(
    dashboardKey: dashboardKey,
    revision: 1,
    updatedAt: null,
    instances: instances,
    layouts: {
      DashboardBreakpoint.desktop: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.desktop,
        columns: 12,
        rowHeight: 110,
        gap: 20,
        canvasPadding: 10,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'client_profile_1',
            'client_profile',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 0,
            w: 8,
            h: 2,
          ),
          _item(
            registry,
            'client_todo_1',
            'client_todo',
            DashboardBreakpoint.desktop,
            x: 8,
            y: 0,
            w: 4,
            h: 6,
          ),
          _item(
            registry,
            'client_details_1',
            'client_details',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 2,
            w: 3,
            h: 3,
          ),
          _item(
            registry,
            'client_events_1',
            'client_events',
            DashboardBreakpoint.desktop,
            x: 3,
            y: 2,
            w: 5,
            h: 3,
          ),
          _item(
            registry,
            'client_transactions_1',
            'client_transactions',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 5,
            w: 8,
            h: 4,
          ),
        ],
      ),
      DashboardBreakpoint.tablet: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.tablet,
        columns: 8,
        rowHeight: 100,
        gap: 16,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'client_profile_1',
            'client_profile',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 0,
            w: 8,
            h: 2,
          ),
          _item(
            registry,
            'client_details_1',
            'client_details',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 2,
            w: 8,
            h: 3,
          ),
          _item(
            registry,
            'client_events_1',
            'client_events',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 5,
            w: 8,
            h: 3,
          ),
          _item(
            registry,
            'client_todo_1',
            'client_todo',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 8,
            w: 8,
            h: 4,
          ),
          _item(
            registry,
            'client_transactions_1',
            'client_transactions',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 12,
            w: 8,
            h: 4,
          ),
        ],
      ),
      DashboardBreakpoint.mobile: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.mobile,
        columns: 4,
        rowHeight: 92,
        gap: 12,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'client_profile_1',
            'client_profile',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 0,
            w: 4,
            h: 3,
          ),
          _item(
            registry,
            'client_details_1',
            'client_details',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 3,
            w: 4,
            h: 3,
          ),
          _item(
            registry,
            'client_events_1',
            'client_events',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 6,
            w: 4,
            h: 4,
          ),
          _item(
            registry,
            'client_todo_1',
            'client_todo',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 10,
            w: 4,
            h: 4,
          ),
          _item(
            registry,
            'client_transactions_1',
            'client_transactions',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 14,
            w: 4,
            h: 5,
          ),
        ],
      ),
    },
  );
}





DashboardConfig _buildCrmUserPanelDashboardConfig({
  required String dashboardKey,
  required DashboardWidgetRegistry registry,
}) {
  const instances = [
    DashboardWidgetInstance(
      id: 'crm_user_welcome_header_1',
      type: 'welcome_header',
      titleOverride: 'CRM User Panel',
    ),
    DashboardWidgetInstance(
      id: 'crm_user_company_members_1',
      type: 'company_members',
      settings: {
        'compact': false,
      },
    ),
    DashboardWidgetInstance(
      id: 'crm_user_calendar_1',
      type: 'calendar',
    ),
    DashboardWidgetInstance(
      id: 'crm_user_tasks_1',
      type: 'tms_tasks',
      settings: {
        'filter': 'latest',
        'layout': 'auto',
        'limit': 10,
        'showBoardSwitcher': true,
        'showSyncStatus': true,
        'showStats': true,
        'compact': false,
      },
    ),
    DashboardWidgetInstance(
      id: 'crm_user_mail_1',
      type: 'mail',
      settings: {
        'filter': 'latest',
        'layout': 'auto',
        'limit': 8,
        'showPreview': true,
        'showAccountSwitcher': true,
        'compact': false,
      },
    ),
    DashboardWidgetInstance(
      id: 'crm_user_cloud_recent_1',
      type: 'cloud_recent',
      settings: {
        'mode': 'mixed',
        'layout': 'auto',
        'showQuota': true,
        'showUpload': true,
        'enableDrop': true,
        'compact': false,
        'cloudRoute': '/cloud',
      },
    ),
  ];

  return DashboardConfig(
    dashboardKey: dashboardKey,
    revision: 1,
    updatedAt: null,
    instances: instances,
    layouts: {
      DashboardBreakpoint.desktop: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.desktop,
        columns: 12,
        rowHeight: 110,
        gap: 20,
        canvasPadding: 10,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'crm_user_welcome_header_1',
            'welcome_header',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 0,
            w: 12,
            h: 1,
          ),
          _item(
            registry,
            'crm_user_company_members_1',
            'company_members',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 1,
            w: 4,
            h: 3,
          ),
          _item(
            registry,
            'crm_user_tasks_1',
            'tms_tasks',
            DashboardBreakpoint.desktop,
            x: 4,
            y: 1,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_calendar_1',
            'calendar',
            DashboardBreakpoint.desktop,
            x: 8,
            y: 1,
            w: 4,
            h: 6,
          ),
          _item(
            registry,
            'crm_user_mail_1',
            'mail',
            DashboardBreakpoint.desktop,
            x: 0,
            y: 4,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_cloud_recent_1',
            'cloud_recent',
            DashboardBreakpoint.desktop,
            x: 4,
            y: 6,
            w: 4,
            h: 5,
          ),
        ],
      ),
      DashboardBreakpoint.tablet: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.tablet,
        columns: 8,
        rowHeight: 100,
        gap: 16,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'crm_user_welcome_header_1',
            'welcome_header',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 0,
            w: 8,
            h: 1,
          ),
          _item(
            registry,
            'crm_user_company_members_1',
            'company_members',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 1,
            w: 4,
            h: 3,
          ),
          _item(
            registry,
            'crm_user_calendar_1',
            'calendar',
            DashboardBreakpoint.tablet,
            x: 4,
            y: 1,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_tasks_1',
            'tms_tasks',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 4,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_mail_1',
            'mail',
            DashboardBreakpoint.tablet,
            x: 4,
            y: 6,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_cloud_recent_1',
            'cloud_recent',
            DashboardBreakpoint.tablet,
            x: 0,
            y: 9,
            w: 4,
            h: 5,
          ),
        ],
      ),
      DashboardBreakpoint.mobile: DashboardBreakpointLayout(
        breakpoint: DashboardBreakpoint.mobile,
        columns: 4,
        rowHeight: 92,
        gap: 12,
        canvasPadding: 8,
        horizontalPadding: 16,
        items: [
          _item(
            registry,
            'crm_user_welcome_header_1',
            'welcome_header',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 0,
            w: 4,
            h: 1,
          ),
          _item(
            registry,
            'crm_user_company_members_1',
            'company_members',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 1,
            w: 4,
            h: 2,
          ),
          _item(
            registry,
            'crm_user_calendar_1',
            'calendar',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 3,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_tasks_1',
            'tms_tasks',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 8,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_mail_1',
            'mail',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 13,
            w: 4,
            h: 5,
          ),
          _item(
            registry,
            'crm_user_cloud_recent_1',
            'cloud_recent',
            DashboardBreakpoint.mobile,
            x: 0,
            y: 18,
            w: 4,
            h: 5,
          ),
        ],
      ),
    },
  );
}