# Generated by Django 5.1.6 on 2026-07-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zrodlo",
                    models.CharField(
                        choices=[
                            ("bzp", "BZP (ezamówienia.gov.pl)"),
                            ("ted", "TED (europa.eu)"),
                            ("manual", "Ręcznie dodany"),
                        ],
                        max_length=20,
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("count_fetched", models.IntegerField(default=0)),
                ("count_new", models.IntegerField(default=0)),
                ("blad", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SubskrypcjaPrzetargow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("nazwa", models.CharField(default="Domyślna", max_length=100)),
                (
                    "cpv_kody",
                    models.JSONField(
                        default=list,
                        help_text='Kody CPV np. ["45000000-7", "45210000-2"]',
                    ),
                ),
                (
                    "regiony",
                    models.JSONField(
                        default=list,
                        help_text='Województwa np. ["małopolskie", "śląskie"]',
                    ),
                ),
                (
                    "wartosc_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "wartosc_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "slowa_kluczowe",
                    models.JSONField(
                        default=list,
                        help_text='Słowa kluczowe w tytule/opisie np. ["budynek", "remont"]',
                    ),
                ),
                ("aktywna", models.BooleanField(default=True)),
                ("ostatnie_pobranie", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Przetarg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("tytul", models.CharField(max_length=500)),
                ("zamawiajacy", models.CharField(max_length=300)),
                ("opis", models.TextField(blank=True)),
                (
                    "wartosc_szacunkowa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("waluta", models.CharField(default="PLN", max_length=3)),
                ("termin_skladania", models.DateTimeField(blank=True, null=True)),
                ("termin_realizacji", models.DateField(blank=True, null=True)),
                ("lokalizacja", models.CharField(blank=True, max_length=200)),
                ("cpv_kody", models.JSONField(default=list)),
                (
                    "zrodlo",
                    models.CharField(
                        choices=[
                            ("bzp", "BZP (ezamówienia.gov.pl)"),
                            ("ted", "TED (europa.eu)"),
                            ("manual", "Ręcznie dodany"),
                        ],
                        default="bzp",
                        max_length=20,
                    ),
                ),
                ("zrodlo_id", models.CharField(blank=True, max_length=100)),
                ("zrodlo_url", models.URLField(blank=True, max_length=500)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nowy", "Nowy"),
                            ("analizowany", "Analizowany"),
                            ("kosztorys_gotowy", "Kosztorys gotowy"),
                            ("zlozony", "Złożony"),
                            ("wygrany", "Wygrany"),
                            ("przegrany", "Przegrany"),
                            ("pominiety", "Pominięty"),
                        ],
                        default="nowy",
                        max_length=20,
                    ),
                ),
                ("ai_score", models.IntegerField(blank=True, null=True)),
                ("ai_uzasadnienie", models.TextField(blank=True)),
                ("ai_czy_warto", models.BooleanField(blank=True, null=True)),
                ("ai_uwagi", models.JSONField(default=list)),
                ("ai_analizowany_at", models.DateTimeField(blank=True, null=True)),
                ("kosztorys_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_id", "status"],
                        name="przetargi_p_company_8d4196_idx",
                    ),
                    models.Index(
                        fields=["company_id", "termin_skladania"],
                        name="przetargi_p_company_bfb804_idx",
                    ),
                ],
                "unique_together": {("zrodlo", "zrodlo_id", "company_id")},
            },
        ),
    ]
