# Generated by Django 5.1.6 on 2026-07-09 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("przetargi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmmaWiadomoscPrzetargu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("tekst", models.TextField()),
                ("kosztorys_id", models.IntegerField(blank=True, null=True)),
                ("przeczytana", models.BooleanField(default=False)),
                ("zaakceptowana", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "przetarg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emma_wiadomosci",
                        to="przetargi.przetarg",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
