# Generated by Django 5.1.6 on 2026-07-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pracownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("imie", models.CharField(max_length=100)),
                ("nazwisko", models.CharField(max_length=100)),
                ("telefon", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("pesel", models.CharField(blank=True, max_length=11)),
                ("numer_umowy", models.CharField(blank=True, max_length=50)),
                (
                    "typ_umowy",
                    models.CharField(
                        choices=[
                            ("umowa_o_prace", "Umowa o pracę"),
                            ("umowa_zlecenie", "Umowa zlecenie"),
                            ("b2b", "B2B"),
                            ("dzieło", "Umowa o dzieło"),
                        ],
                        default="umowa_zlecenie",
                        max_length=20,
                    ),
                ),
                (
                    "glowna_specjalizacja",
                    models.CharField(
                        choices=[
                            ("murarz", "Murarz"),
                            ("zbrojarz", "Zbrojarz / betoniar"),
                            ("ciesla", "Cieśla"),
                            ("dekarz", "Dekarz"),
                            ("tynkarz", "Tynkarz / glazurnik"),
                            ("instalator_wod_kan", "Instalator wod-kan"),
                            ("elektryk", "Elektryk"),
                            ("spawacz", "Spawacz"),
                            ("operator", "Operator sprzętu"),
                            ("kierownik", "Kierownik budowy"),
                            ("geodeta", "Geodeta"),
                            ("pomocnik", "Pomocnik budowlany"),
                            ("inne", "Inne"),
                        ],
                        default="pomocnik",
                        max_length=30,
                    ),
                ),
                ("aktywny", models.BooleanField(default=True)),
                ("data_zatrudnienia", models.DateField(blank=True, null=True)),
                ("uwagi", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nazwisko", "imie"],
            },
        ),
        migrations.CreateModel(
            name="HistoriaStawki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stawka_godz", models.DecimalField(decimal_places=2, max_digits=8)),
                ("waluta", models.CharField(default="PLN", max_length=5)),
                ("data_od", models.DateField()),
                ("uwagi", models.CharField(blank=True, max_length=255)),
                (
                    "pracownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stawki",
                        to="pracownicy.pracownik",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_od"],
            },
        ),
        migrations.CreateModel(
            name="PracownikNaBudowie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("budowa_id", models.IntegerField(db_index=True)),
                ("etap_id", models.IntegerField(blank=True, null=True)),
                ("rola_na_budowie", models.CharField(blank=True, max_length=100)),
                ("data_od", models.DateField(blank=True, null=True)),
                ("data_do", models.DateField(blank=True, null=True)),
                ("aktywny", models.BooleanField(default=True)),
                (
                    "pracownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budowy",
                        to="pracownicy.pracownik",
                    ),
                ),
            ],
            options={
                "unique_together": {("pracownik", "budowa_id")},
            },
        ),
        migrations.CreateModel(
            name="UmiejetnoscPracownika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specjalizacja",
                    models.CharField(
                        choices=[
                            ("murarz", "Murarz"),
                            ("zbrojarz", "Zbrojarz / betoniar"),
                            ("ciesla", "Cieśla"),
                            ("dekarz", "Dekarz"),
                            ("tynkarz", "Tynkarz / glazurnik"),
                            ("instalator_wod_kan", "Instalator wod-kan"),
                            ("elektryk", "Elektryk"),
                            ("spawacz", "Spawacz"),
                            ("operator", "Operator sprzętu"),
                            ("kierownik", "Kierownik budowy"),
                            ("geodeta", "Geodeta"),
                            ("pomocnik", "Pomocnik budowlany"),
                            ("inne", "Inne"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "poziom",
                    models.CharField(
                        choices=[
                            ("uczen", "Uczeń / staż"),
                            ("junior", "Junior (1-3 lata)"),
                            ("mid", "Samodzielny (3-8 lat)"),
                            ("senior", "Senior (8-15 lat)"),
                            ("ekspert", "Ekspert (15+ lat)"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                ("lata_doswiadczenia", models.PositiveSmallIntegerField(default=0)),
                ("certyfikat", models.CharField(blank=True, max_length=255)),
                ("numer_certyfikatu", models.CharField(blank=True, max_length=100)),
                ("certyfikat_wazny_do", models.DateField(blank=True, null=True)),
                (
                    "stawka_specjalizacji",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("uwagi", models.TextField(blank=True)),
                (
                    "pracownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="umiejetnosci",
                        to="pracownicy.pracownik",
                    ),
                ),
            ],
            options={
                "ordering": ["specjalizacja"],
                "unique_together": {("pracownik", "specjalizacja")},
            },
        ),
    ]
