# Generated by Django 5.1.6 on 2026-07-09 05:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budowa", "0002_budowa_lat_budowa_lon"),
        ("oferty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faktura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("numer", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("sprzedaz", "Faktura sprzedaży"),
                            ("zaliczkowa", "Faktura zaliczkowa"),
                            ("koncowa", "Faktura końcowa"),
                            ("korygujaca", "Faktura korygująca"),
                            ("proforma", "Proforma"),
                        ],
                        default="sprzedaz",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("szkic", "Szkic"),
                            ("wystawiona", "Wystawiona"),
                            ("wyslana", "Wysłana"),
                            ("oplacona", "Opłacona"),
                            ("przeterminowana", "Przeterminowana"),
                            ("anulowana", "Anulowana"),
                        ],
                        default="szkic",
                        max_length=20,
                    ),
                ),
                ("wystawca_nazwa", models.CharField(default="", max_length=255)),
                ("wystawca_nip", models.CharField(blank=True, max_length=20)),
                ("wystawca_adres", models.TextField(blank=True)),
                ("wystawca_konto", models.CharField(blank=True, max_length=34)),
                ("nabywca_nazwa", models.CharField(max_length=255)),
                ("nabywca_nip", models.CharField(blank=True, max_length=20)),
                ("nabywca_adres", models.TextField(blank=True)),
                (
                    "data_wystawienia",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("data_sprzedazy", models.DateField(blank=True, null=True)),
                ("termin_platnosci", models.DateField()),
                (
                    "metoda_platnosci",
                    models.CharField(
                        choices=[
                            ("przelew", "Przelew bankowy"),
                            ("gotowka", "Gotówka"),
                            ("karta", "Karta płatnicza"),
                            ("blik", "BLIK"),
                        ],
                        default="przelew",
                        max_length=15,
                    ),
                ),
                ("pozycje", models.JSONField(default=list)),
                (
                    "wartosc_netto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wartosc_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wartosc_brutto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("stawka_vat", models.IntegerField(default=23)),
                ("uwagi", models.TextField(blank=True)),
                ("pdf_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_oplacenia", models.DateField(blank=True, null=True)),
                (
                    "budowa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faktury",
                        to="budowa.budowa",
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faktury",
                        to="oferty.oferta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "faktury",
                "ordering": ["-data_wystawienia", "-id"],
            },
        ),
    ]
