# Generated by Django 5.2.16 on 2026-07-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnrKatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=20, unique=True)),
                ("nazwa", models.CharField(max_length=255)),
                ("opis", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "katalogi KNR",
            },
        ),
        migrations.CreateModel(
            name="Kosztorys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                (
                    "budowa_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("opis", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("roboczy", "Roboczy"),
                            ("oferta", "Oferta"),
                            ("zatwierdzony", "Zatwierdzony"),
                        ],
                        default="roboczy",
                        max_length=20,
                    ),
                ),
                ("ai_prompt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "kosztorysy",
            },
        ),
        migrations.CreateModel(
            name="KnrPozycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numer", models.CharField(max_length=30)),
                ("opis", models.TextField()),
                ("jednostka", models.CharField(max_length=20)),
                (
                    "naklad_r",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "naklad_m",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "naklad_s",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "katalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pozycje",
                        to="kosztorysy.knrkatalog",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pozycje KNR",
                "unique_together": {("katalog", "numer")},
            },
        ),
        migrations.CreateModel(
            name="KosztorysdzDzial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("kolejnosc", models.PositiveIntegerField(default=0)),
                (
                    "kosztorys",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dzialy",
                        to="kosztorysy.kosztorys",
                    ),
                ),
            ],
            options={
                "ordering": ["kolejnosc"],
            },
        ),
        migrations.CreateModel(
            name="KosztorysPozycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis", models.TextField()),
                ("jednostka", models.CharField(max_length=20)),
                ("ilosc", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "cena_jednostkowa",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("kolejnosc", models.PositiveIntegerField(default=0)),
                (
                    "ai_suggested_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ai_suggested_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "dzial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pozycje",
                        to="kosztorysy.kosztorysdzdzial",
                    ),
                ),
                (
                    "knr_pozycja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kosztorysy.knrpozycja",
                    ),
                ),
            ],
            options={
                "ordering": ["kolejnosc"],
            },
        ),
    ]
