name: przetargi
description: "Moduł wyszukiwania przetargów budowlanych — budkon.pro"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../../core
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  intl: any
