# Generated by Django 5.1.6 on 2026-07-09 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budowa", "0002_budowa_lat_budowa_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneHarmonogramu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("nazwa", models.CharField(max_length=255)),
                ("data", models.DateField()),
                ("osiagniety", models.BooleanField(default=False)),
                ("kolor", models.CharField(default="#FF9800", max_length=7)),
                (
                    "budowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="budowa.budowa",
                    ),
                ),
                (
                    "etap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budowa.etapbudowy",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="ZadanieHarmonogramu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("nazwa", models.CharField(max_length=255)),
                ("opis", models.TextField(blank=True)),
                ("kolejnosc", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planowane", "Planowane"),
                            ("w_toku", "W toku"),
                            ("zakonczone", "Zakończone"),
                            ("wstrzymane", "Wstrzymane"),
                        ],
                        default="planowane",
                        max_length=20,
                    ),
                ),
                ("data_start", models.DateField(blank=True, null=True)),
                ("data_koniec", models.DateField(blank=True, null=True)),
                (
                    "czas_trwania_dni",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("postep_procent", models.PositiveSmallIntegerField(default=0)),
                (
                    "budzet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("kosztorys_id", models.IntegerField(blank=True, null=True)),
                ("assigned_ids", models.JSONField(blank=True, default=list)),
                (
                    "budowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zadania",
                        to="budowa.budowa",
                    ),
                ),
                (
                    "etap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zadania",
                        to="budowa.etapbudowy",
                    ),
                ),
                (
                    "poprzednicy",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nastepniki",
                        to="harmonogram.zadanieharmonogramu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "zadania harmonogramu",
                "ordering": ["kolejnosc", "data_start"],
            },
        ),
    ]
