# Generated by Django 5.1.6 on 2026-07-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budowa", "0002_budowa_lat_budowa_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalKlienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("nazwa_klienta", models.CharField(max_length=255)),
                ("email_klienta", models.EmailField(blank=True, max_length=254)),
                ("telefon_klienta", models.CharField(blank=True, max_length=30)),
                ("pokazuj_kosztorys", models.BooleanField(default=False)),
                ("pokazuj_faktury", models.BooleanField(default=True)),
                ("pokazuj_zdjecia", models.BooleanField(default=True)),
                ("pokazuj_harmonogram", models.BooleanField(default=True)),
                ("aktywny", models.BooleanField(default=True)),
                ("wygasa", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ostatni_odczyt", models.DateTimeField(blank=True, null=True)),
                ("liczba_odczytow", models.IntegerField(default=0)),
                (
                    "budowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portale",
                        to="budowa.budowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal klienta",
                "verbose_name_plural": "Portale klientów",
            },
        ),
    ]
