# Generated by Django 5.2.16 on 2026-07-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("nazwa", models.CharField(max_length=255)),
                ("adres", models.CharField(blank=True, max_length=500)),
                ("zamawiajacy_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("oferta", "Oferta"),
                            ("umowa", "Umowa podpisana"),
                            ("w_toku", "W toku"),
                            ("zakonczona", "Zakończona"),
                            ("anulowana", "Anulowana"),
                        ],
                        default="oferta",
                        max_length=30,
                    ),
                ),
                ("data_rozpoczecia", models.DateField(blank=True, null=True)),
                (
                    "data_planowanego_zakonczenia",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "budzet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "budowy",
            },
        ),
        migrations.CreateModel(
            name="EtapBudowy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                (
                    "typ",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("projekt", "Projekt"),
                            ("pozwolenie", "Pozwolenie na budowę"),
                            ("fundamenty", "Fundamenty"),
                            ("stan_surowy", "Stan surowy zamknięty"),
                            ("dach", "Dach"),
                            ("instalacje", "Instalacje"),
                            ("wykonczenie", "Wykończenie"),
                            ("odbiory", "Odbiory"),
                            ("gwarancja", "Okres gwarancji"),
                        ],
                        max_length=30,
                    ),
                ),
                ("kolejnosc", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planowany", "Planowany"),
                            ("w_toku", "W toku"),
                            ("zakończony", "Zakończony"),
                        ],
                        default="planowany",
                        max_length=20,
                    ),
                ),
                ("data_start", models.DateField(blank=True, null=True)),
                ("data_koniec", models.DateField(blank=True, null=True)),
                (
                    "budzet_etapu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("kosztorys_id", models.IntegerField(blank=True, null=True)),
                (
                    "budowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapy",
                        to="budowa.budowa",
                    ),
                ),
            ],
            options={
                "ordering": ["kolejnosc"],
            },
        ),
    ]
