# Generated by Django 5.1.6 on 2026-07-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budowa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budowa",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budowa",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
