import 'package:core/ui/anchors/anchor_spec.dart';

abstract final class DocsEmmaAnchors {
  static const String _module = 'docs';
  static const String _route = '/docs';


  static const EmmaUiAnchorSpec documentEditorScreen = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.screen',
    frontendRef: 'DocsEmmaAnchors.documentEditorScreen',
    label: 'Document Editor Screen',
    description: 'Main document editing screen with Quill editor.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.section,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'editor', 'screen'],
    meta: {'group': 'screen'},
    onboardingOrder: 1,
    onboardingMessage: 'This is your document editor workspace.',
  );

  static const EmmaUiAnchorSpec documentTitleEditor = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.title',
    frontendRef: 'DocsEmmaAnchors.documentTitleEditor',
    label: 'Document Title Editor',
    description: 'Editable document title field.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'title', 'input'],
    meta: {'group': 'header'},
    onboardingOrder: 2,
    onboardingMessage: 'Click here to edit the document title.',
  );

  static const EmmaUiAnchorSpec goToDocumentsButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.go_to_documents',
    frontendRef: 'DocsEmmaAnchors.goToDocumentsButton',
    label: 'Go to Documents Button',
    description: 'Button to navigate to documents list.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'navigation', 'documents', 'button'],
    meta: {'group': 'navigation'},
  );

  static const EmmaUiAnchorSpec goToTemplatesButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.go_to_templates',
    frontendRef: 'DocsEmmaAnchors.goToTemplatesButton',
    label: 'Go to Templates Button',
    description: 'Button to navigate to templates list.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'navigation', 'templates', 'button'],
    meta: {'group': 'navigation'},
  );

  static const EmmaUiAnchorSpec saveTemplateButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.save_template',
    frontendRef: 'DocsEmmaAnchors.saveTemplateButton',
    label: 'Save Template Button',
    description: 'Button to save current document as template.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'template', 'save', 'button'],
    meta: {'group': 'template_actions'},
  );

  static const EmmaUiAnchorSpec connectionChip = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.connection_status',
    frontendRef: 'DocsEmmaAnchors.connectionChip',
    label: 'Connection Status',
    description: 'Shows WebSocket connection status (Saved/Connecting).',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.widget,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'connection', 'status'],
    meta: {'group': 'status'},
  );

  static const EmmaUiAnchorSpec quillEditor = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.quill',
    frontendRef: 'DocsEmmaAnchors.quillEditor',
    label: 'Document Editor',
    description: 'Main Quill text editor for document content.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.section,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'editor', 'quill', 'content'],
    meta: {'group': 'content'},
    onboardingOrder: 3,
    onboardingMessage: 'Write and edit your document content here.',
  );

  static const EmmaUiAnchorSpec docsQuillToolbar = EmmaUiAnchorSpec(
    anchorKey: 'docs.editor.toolbar',
    frontendRef: 'DocsEmmaAnchors.docsQuillToolbar',
    label: 'Document Toolbar',
    description: 'Formatting toolbar for text editing.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.section,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'toolbar', 'formatting'],
    meta: {'group': 'toolbar'},
    onboardingOrder: 4,
    onboardingMessage: 'Use this toolbar to format your document text.',
  );

  static const EmmaUiAnchorSpec docsMobileToolbarStrip = EmmaUiAnchorSpec(
    anchorKey: 'docs.mobile.toolbar',
    frontendRef: 'DocsEmmaAnchors.docsMobileToolbarStrip',
    label: 'Mobile Toolbar Strip',
    description: 'Bottom toolbar strip for mobile document editing.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.section,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'mobile', 'toolbar'],
    meta: {'group': 'toolbar', 'platform': 'mobile'},
  );

  static const EmmaUiAnchorSpec saveDocumentButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.toolbar.save_document',
    frontendRef: 'DocsEmmaAnchors.saveDocumentButton',
    label: 'Save Document Button',
    description: 'Button to save the current document.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'save', 'document', 'button'],
    meta: {'group': 'toolbar_actions'},
  );

  static const EmmaUiAnchorSpec saveVersionButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.toolbar.save_version',
    frontendRef: 'DocsEmmaAnchors.saveVersionButton',
    label: 'Save Version Button',
    description: 'Button to save a version of the document.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'save', 'version', 'button'],
    meta: {'group': 'toolbar_actions'},
  );

  static const EmmaUiAnchorSpec generatePdfButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.toolbar.generate_pdf',
    frontendRef: 'DocsEmmaAnchors.generatePdfButton',
    label: 'Generate PDF Button',
    description: 'Button to generate PDF from document.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'pdf', 'generate', 'button'],
    meta: {'group': 'toolbar_actions'},
  );

  static const EmmaUiAnchorSpec insertLinkButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.toolbar.insert_link',
    frontendRef: 'DocsEmmaAnchors.insertLinkButton',
    label: 'Insert Link Button',
    description: 'Button to insert a hyperlink in the document.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'link', 'insert', 'button'],
    meta: {'group': 'toolbar_actions'},
  );

  static const EmmaUiAnchorSpec searchButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.toolbar.search',
    frontendRef: 'DocsEmmaAnchors.searchButton',
    label: 'Search Button',
    description: 'Button to search within the document.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'search', 'find', 'button'],
    meta: {'group': 'toolbar_actions'},
  );

  static const EmmaUiAnchorSpec textColorButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.toolbar.text_color',
    frontendRef: 'DocsEmmaAnchors.textColorButton',
    label: 'Text Color Button',
    description: 'Button to change text color.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'color', 'text', 'button'],
    meta: {'group': 'toolbar_actions'},
  );

  static const EmmaUiAnchorSpec backgroundColorButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.toolbar.background_color',
    frontendRef: 'DocsEmmaAnchors.backgroundColorButton',
    label: 'Background Color Button',
    description: 'Button to change text background color.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'color', 'background', 'button'],
    meta: {'group': 'toolbar_actions'},
  );

  static const EmmaUiAnchorSpec createDocumentDialog = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.root',
    frontendRef: 'DocsEmmaAnchors.createDocumentDialog',
    label: 'Create Document Dialog',
    description: 'Dialog for creating new documents or selecting templates.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'dialog', 'create'],
    meta: {'group': 'dialog'},
    onboardingOrder: 5,
    onboardingMessage: 'Create a new document or choose from templates.',
  );

  static const EmmaUiAnchorSpec documentsTab = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.documents_tab',
    frontendRef: 'DocsEmmaAnchors.documentsTab',
    label: 'Documents Tab',
    description: 'Tab showing user\'s documents.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.tab,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'tab', 'documents'],
    meta: {'group': 'tabs'},
  );

  static const EmmaUiAnchorSpec templatesTab = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.templates_tab',
    frontendRef: 'DocsEmmaAnchors.templatesTab',
    label: 'Templates Tab',
    description: 'Tab showing available templates.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.tab,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'tab', 'templates'],
    meta: {'group': 'tabs'},
  );

  static const EmmaUiAnchorSpec documentFilterBar = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.filter_bar',
    frontendRef: 'DocsEmmaAnchors.documentFilterBar',
    label: 'Document Filter Bar',
    description: 'Search and filter bar for documents/templates.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.section,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'filter', 'search'],
    meta: {'group': 'filters'},
  );

  static const EmmaUiAnchorSpec finalizedOnlyFilter = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.finalized_filter',
    frontendRef: 'DocsEmmaAnchors.finalizedOnlyFilter',
    label: 'Finalized Only Filter',
    description: 'Filter chip to show only finalized documents.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'filter', 'finalized'],
    meta: {'group': 'filters'},
  );

  static const EmmaUiAnchorSpec globalTemplatesFilter = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.global_filter',
    frontendRef: 'DocsEmmaAnchors.globalTemplatesFilter',
    label: 'Global Templates Filter',
    description: 'Filter chip to show only global templates.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'filter', 'global'],
    meta: {'group': 'filters'},
  );

  static const EmmaUiAnchorSpec dateFilterButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.date_filter',
    frontendRef: 'DocsEmmaAnchors.dateFilterButton',
    label: 'Date Filter Button',
    description: 'Button to filter by date range.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'filter', 'date'],
    meta: {'group': 'filters'},
  );

  static const EmmaUiAnchorSpec sortButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.sort',
    frontendRef: 'DocsEmmaAnchors.sortButton',
    label: 'Sort Button',
    description: 'Button to sort documents/templates.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'sort', 'order'],
    meta: {'group': 'filters'},
  );

  static const EmmaUiAnchorSpec clearFiltersButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.clear_filters',
    frontendRef: 'DocsEmmaAnchors.clearFiltersButton',
    label: 'Clear Filters Button',
    description: 'Button to clear all active filters.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'clear', 'filters'],
    meta: {'group': 'filters'},
  );

  static const EmmaUiAnchorSpec documentListItem = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.document_item',
    frontendRef: 'DocsEmmaAnchors.documentListItem',
    label: 'Document List Item',
    description: 'Individual document item in the list.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.listItem,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'document', 'list', 'item'],
    meta: {'group': 'list'},
  );

  static const EmmaUiAnchorSpec templateListItem = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.template_item',
    frontendRef: 'DocsEmmaAnchors.templateListItem',
    label: 'Template List Item',
    description: 'Individual template item in the list.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.listItem,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'template', 'list', 'item'],
    meta: {'group': 'list'},
  );

  static const EmmaUiAnchorSpec editTemplateButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.edit_template',
    frontendRef: 'DocsEmmaAnchors.editTemplateButton',
    label: 'Edit Template Button',
    description: 'Button to edit existing template.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'template', 'edit', 'button'],
    meta: {'group': 'template_actions'},
  );

  static const EmmaUiAnchorSpec createFromTemplateButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.create_from_template',
    frontendRef: 'DocsEmmaAnchors.createFromTemplateButton',
    label: 'Create from Template Button',
    description: 'Button to create new document from template.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'template', 'create', 'button'],
    meta: {'group': 'template_actions'},
  );

  static const EmmaUiAnchorSpec deleteDocumentButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.delete_document',
    frontendRef: 'DocsEmmaAnchors.deleteDocumentButton',
    label: 'Delete Document Button',
    description: 'Button to delete document from list.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'document', 'delete', 'button'],
    meta: {'group': 'actions'},
  );

  static const EmmaUiAnchorSpec deleteTemplateButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_dialog.delete_template',
    frontendRef: 'DocsEmmaAnchors.deleteTemplateButton',
    label: 'Delete Template Button',
    description: 'Button to delete template from list.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'template', 'delete', 'button'],
    meta: {'group': 'actions'},
  );

  static const EmmaUiAnchorSpec closeDialogButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.dialog.close_button',
    frontendRef: 'DocsEmmaAnchors.closeDialogButton',
    label: 'Close Dialog Button',
    description: 'Button to close the current dialog.',
    module: _module,
    screenKey: 'create_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'dialog', 'close', 'button'],
    meta: {'group': 'dialog_actions'},
  );

  // ==================== CREATE TEMPLATE DIALOG/SHEET ====================
  static const EmmaUiAnchorSpec createTemplateDialog = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_template.dialog',
    frontendRef: 'DocsEmmaAnchors.createTemplateDialog',
    label: 'Create Template Dialog',
    description: 'Dialog for creating new templates.',
    module: _module,
    screenKey: 'create_template',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'template', 'dialog'],
    meta: {'group': 'dialogs'},
  );

  static const EmmaUiAnchorSpec createTemplateSheet = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_template.sheet',
    frontendRef: 'DocsEmmaAnchors.createTemplateSheet',
    label: 'Create Template Sheet',
    description: 'Bottom sheet for creating new templates.',
    module: _module,
    screenKey: 'create_template',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'template', 'sheet'],
    meta: {'group': 'dialogs', 'platform': 'mobile'},
  );

  static const EmmaUiAnchorSpec templateNameField = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_template.name_field',
    frontendRef: 'DocsEmmaAnchors.templateNameField',
    label: 'Template Name Field',
    description: 'Input field for template name.',
    module: _module,
    screenKey: 'create_template',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'template', 'name', 'input'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec templateDescriptionField = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_template.description_field',
    frontendRef: 'DocsEmmaAnchors.templateDescriptionField',
    label: 'Template Description Field',
    description: 'Input field for template description.',
    module: _module,
    screenKey: 'create_template',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'template', 'description', 'input'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec createTemplateConfirmButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_template.confirm_button',
    frontendRef: 'DocsEmmaAnchors.createTemplateConfirmButton',
    label: 'Create Template Confirm Button',
    description: 'Button to confirm template creation.',
    module: _module,
    screenKey: 'create_template',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'template', 'create', 'confirm'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec cancelTemplateButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.create_template.cancel_button',
    frontendRef: 'DocsEmmaAnchors.cancelTemplateButton',
    label: 'Cancel Template Button',
    description: 'Button to cancel template creation.',
    module: _module,
    screenKey: 'create_template',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'template', 'cancel'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec deleteConfirmationDialog = EmmaUiAnchorSpec(
    anchorKey: 'docs.delete_confirmation.dialog',
    frontendRef: 'DocsEmmaAnchors.deleteConfirmationDialog',
    label: 'Delete Confirmation Dialog',
    description: 'Dialog to confirm deletion of document or template.',
    module: _module,
    screenKey: 'delete_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'delete', 'confirmation', 'dialog'],
    meta: {'group': 'dialogs'},
  );

  static const EmmaUiAnchorSpec confirmDeleteButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.delete_confirmation.confirm',
    frontendRef: 'DocsEmmaAnchors.confirmDeleteButton',
    label: 'Confirm Delete Button',
    description: 'Button to confirm deletion.',
    module: _module,
    screenKey: 'delete_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'delete', 'confirm'],
    meta: {'group': 'dialog_actions'},
  );

  static const EmmaUiAnchorSpec cancelDeleteButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.delete_confirmation.cancel',
    frontendRef: 'DocsEmmaAnchors.cancelDeleteButton',
    label: 'Cancel Delete Button',
    description: 'Button to cancel deletion.',
    module: _module,
    screenKey: 'delete_dialog',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'delete', 'cancel'],
    meta: {'group': 'dialog_actions'},
  );

  static const EmmaUiAnchorSpec linkSheet = EmmaUiAnchorSpec(
    anchorKey: 'docs.link.sheet',
    frontendRef: 'DocsEmmaAnchors.linkSheet',
    label: 'Link Sheet',
    description: 'Bottom sheet for inserting/editing links.',
    module: _module,
    screenKey: 'link_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'link', 'sheet'],
    meta: {'group': 'sheets'},
  );

  static const EmmaUiAnchorSpec linkUrlField = EmmaUiAnchorSpec(
    anchorKey: 'docs.link.url_field',
    frontendRef: 'DocsEmmaAnchors.linkUrlField',
    label: 'Link URL Field',
    description: 'Input field for link URL.',
    module: _module,
    screenKey: 'link_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'link', 'url', 'input'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec applyLinkButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.link.apply',
    frontendRef: 'DocsEmmaAnchors.applyLinkButton',
    label: 'Apply Link Button',
    description: 'Button to apply link to selected text.',
    module: _module,
    screenKey: 'link_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'link', 'apply'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec removeLinkButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.link.remove',
    frontendRef: 'DocsEmmaAnchors.removeLinkButton',
    label: 'Remove Link Button',
    description: 'Button to remove link from selected text.',
    module: _module,
    screenKey: 'link_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'link', 'remove'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec searchSheet = EmmaUiAnchorSpec(
    anchorKey: 'docs.search.sheet',
    frontendRef: 'DocsEmmaAnchors.searchSheet',
    label: 'Search Sheet',
    description: 'Bottom sheet for searching within document.',
    module: _module,
    screenKey: 'search_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'search', 'sheet'],
    meta: {'group': 'sheets'},
  );

  static const EmmaUiAnchorSpec searchTextField = EmmaUiAnchorSpec(
    anchorKey: 'docs.search.text_field',
    frontendRef: 'DocsEmmaAnchors.searchTextField',
    label: 'Search Text Field',
    description: 'Input field for search text.',
    module: _module,
    screenKey: 'search_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'search', 'input'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec searchNextButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.search.next',
    frontendRef: 'DocsEmmaAnchors.searchNextButton',
    label: 'Search Next Button',
    description: 'Button to go to next search result.',
    module: _module,
    screenKey: 'search_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'search', 'next'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec searchPreviousButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.search.previous',
    frontendRef: 'DocsEmmaAnchors.searchPreviousButton',
    label: 'Search Previous Button',
    description: 'Button to go to previous search result.',
    module: _module,
    screenKey: 'search_sheet',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'search', 'previous'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec versionCommentSheet = EmmaUiAnchorSpec(
    anchorKey: 'docs.version_comment.sheet',
    frontendRef: 'DocsEmmaAnchors.versionCommentSheet',
    label: 'Version Comment Sheet',
    description: 'Bottom sheet for adding version comment.',
    module: _module,
    screenKey: 'version_comment',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'version', 'comment'],
    meta: {'group': 'sheets'},
  );

  static const EmmaUiAnchorSpec versionCommentDialog = EmmaUiAnchorSpec(
    anchorKey: 'docs.version_comment.dialog',
    frontendRef: 'DocsEmmaAnchors.versionCommentDialog',
    label: 'Version Comment Dialog',
    description: 'Dialog for adding version comment.',
    module: _module,
    screenKey: 'version_comment',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'version', 'comment'],
    meta: {'group': 'dialogs'},
  );

  static const EmmaUiAnchorSpec versionCommentField = EmmaUiAnchorSpec(
    anchorKey: 'docs.version_comment.field',
    frontendRef: 'DocsEmmaAnchors.versionCommentField',
    label: 'Version Comment Field',
    description: 'Input field for version comment.',
    module: _module,
    screenKey: 'version_comment',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'version', 'comment', 'input'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec saveVersionConfirmButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.version_comment.save',
    frontendRef: 'DocsEmmaAnchors.saveVersionConfirmButton',
    label: 'Save Version Confirm Button',
    description: 'Button to confirm saving version.',
    module: _module,
    screenKey: 'version_comment',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'version', 'save'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec dateRangePicker = EmmaUiAnchorSpec(
    anchorKey: 'docs.date_range.picker',
    frontendRef: 'DocsEmmaAnchors.dateRangePicker',
    label: 'Date Range Picker',
    description: 'Date range picker for filtering.',
    module: _module,
    screenKey: 'date_picker',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'date', 'picker'],
    meta: {'group': 'dialogs'},
  );

  static const EmmaUiAnchorSpec startDateInput = EmmaUiAnchorSpec(
    anchorKey: 'docs.date_range.start_date',
    frontendRef: 'DocsEmmaAnchors.startDateInput',
    label: 'Start Date Input',
    description: 'Input field for start date.',
    module: _module,
    screenKey: 'date_picker',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'date', 'start'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec endDateInput = EmmaUiAnchorSpec(
    anchorKey: 'docs.date_range.end_date',
    frontendRef: 'DocsEmmaAnchors.endDateInput',
    label: 'End Date Input',
    description: 'Input field for end date.',
    module: _module,
    screenKey: 'date_picker',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'date', 'end'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec applyDateRangeButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.date_range.apply',
    frontendRef: 'DocsEmmaAnchors.applyDateRangeButton',
    label: 'Apply Date Range Button',
    description: 'Button to apply selected date range.',
    module: _module,
    screenKey: 'date_picker',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'date', 'apply'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec placeholderEditDialog = EmmaUiAnchorSpec(
    anchorKey: 'docs.placeholder.edit_dialog',
    frontendRef: 'DocsEmmaAnchors.placeholderEditDialog',
    label: 'Placeholder Edit Dialog',
    description: 'Dialog for editing template placeholders.',
    module: _module,
    screenKey: 'placeholder',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'placeholder', 'template'],
    meta: {'group': 'dialogs'},
  );

  static const EmmaUiAnchorSpec placeholderGenderDropdown = EmmaUiAnchorSpec(
    anchorKey: 'docs.placeholder.gender_dropdown',
    frontendRef: 'DocsEmmaAnchors.placeholderGenderDropdown',
    label: 'Gender Dropdown',
    description: 'Dropdown for selecting gender placeholder value.',
    module: _module,
    screenKey: 'placeholder',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'placeholder', 'gender'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec placeholderTextField = EmmaUiAnchorSpec(
    anchorKey: 'docs.placeholder.text_field',
    frontendRef: 'DocsEmmaAnchors.placeholderTextField',
    label: 'Placeholder Text Field',
    description: 'Text field for entering placeholder value.',
    module: _module,
    screenKey: 'placeholder',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.input,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'placeholder', 'input'],
    meta: {'group': 'form'},
  );

  static const EmmaUiAnchorSpec savePlaceholderButton = EmmaUiAnchorSpec(
    anchorKey: 'docs.placeholder.save',
    frontendRef: 'DocsEmmaAnchors.savePlaceholderButton',
    label: 'Save Placeholder Button',
    description: 'Button to save placeholder value.',
    module: _module,
    screenKey: 'placeholder',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.button,
    runtimeMode: EmmaUiAnchorRuntimeMode.onDemand,
    tapMode: EmmaUiAnchorTapMode.onHighlightOnly,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'placeholder', 'save'],
    meta: {'group': 'form_actions'},
  );

  static const EmmaUiAnchorSpec docWidget = EmmaUiAnchorSpec(
    anchorKey: 'docs.doc_widget',
    frontendRef: 'DocsEmmaAnchors.docWidget',
    label: 'Document Widget',
    description: 'A4-styled document container widget.',
    module: _module,
    screenKey: 'editor',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.section,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.both,
    tags: ['docs', 'container', 'a4'],
    meta: {'group': 'layout'},
  );

  static const EmmaUiAnchorSpec colorPickerDialog = EmmaUiAnchorSpec(
    anchorKey: 'docs.color_picker.dialog',
    frontendRef: 'DocsEmmaAnchors.colorPickerDialog',
    label: 'Color Picker Dialog',
    description: 'Dialog for selecting text or background color.',
    module: _module,
    screenKey: 'color_picker',
    routePattern: _route,
    targetKind: EmmaUiAnchorTargetKind.overlay,
    runtimeMode: EmmaUiAnchorRuntimeMode.semanticOnly,
    tapMode: EmmaUiAnchorTapMode.disabled,
    usageMode: EmmaUiAnchorUsageMode.help,
    tags: ['docs', 'color', 'picker'],
    meta: {'group': 'dialogs'},
  );
}