# Generated by Django 5.1.6 on 2026-07-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budowa", "0002_budowa_lat_budowa_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kontrahent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("imie", models.CharField(blank=True, max_length=100)),
                ("nazwisko", models.CharField(blank=True, max_length=100)),
                ("firma", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefon", models.CharField(blank=True, max_length=30)),
                ("nip", models.CharField(blank=True, db_index=True, max_length=20)),
                ("adres", models.CharField(blank=True, max_length=500)),
                (
                    "branza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("elektryczna", "Elektryczna"),
                            ("hydrauliczna", "Hydrauliczna / wod-kan"),
                            ("budowlana", "Budowlana / murarstwo"),
                            ("fundamenty", "Fundamenty / ziemna"),
                            ("dach", "Dach / pokrycia"),
                            ("stolarska", "Stolarka / okna-drzwi"),
                            ("wykanczanie", "Wykańczanie / tynki"),
                            ("podlogi", "Podłogi"),
                            ("elewacja", "Elewacja / ocieplenie"),
                            ("instalacje_co", "Instalacje CO / gaz"),
                            ("wentylacja", "Wentylacja / klimat."),
                            ("geodezja", "Geodezja"),
                            ("projekt", "Projektant / architekt"),
                            ("kierownik", "Kierownik budowy"),
                            ("inspektor", "Inspektor nadzoru"),
                            ("transport", "Transport / logistyka"),
                            ("inna", "Inna"),
                        ],
                        max_length=40,
                    ),
                ),
                ("uwagi", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="kontrakty/avatary/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "kontrahenci",
                "ordering": ["nazwisko", "imie", "firma"],
            },
        ),
        migrations.CreateModel(
            name="PowiazaniePodwykonawcy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("rola", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("zaproszony", "Zaproszony"),
                            ("aktywny", "Aktywny"),
                            ("zakonczony", "Zakończony"),
                            ("odrzucony", "Odrzucony"),
                        ],
                        default="aktywny",
                        max_length=20,
                    ),
                ),
                (
                    "wartosc_umowy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("data_od", models.DateField(blank=True, null=True)),
                ("data_do", models.DateField(blank=True, null=True)),
                ("uwagi", models.TextField(blank=True)),
                (
                    "budowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podwykonawcy",
                        to="budowa.budowa",
                    ),
                ),
                (
                    "etap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="podwykonawcy",
                        to="budowa.etapbudowy",
                    ),
                ),
                (
                    "kontrahent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="powiazania",
                        to="kontakty.kontrahent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "powiązania podwykonawców",
                "ordering": ["kontrahent__nazwisko", "kontrahent__firma"],
                "unique_together": {("kontrahent", "budowa")},
            },
        ),
    ]
