import 'package:reports/reports/all_report_page/model/report_list_model.dart';
import 'package:reports/reports/report_pdf_page/models/government_data_model.dart';
import 'package:reports/reports/report_pdf_page/models/pdf_report_model.dart';

class SampleReportData {
  static List<ReportsListModel> getSampleReportsList() {
    return [
      ReportsListModel(
        id: 1,
        user: 1,
        country: 'Polska',
        state: 'Mazowieckie',
        city: 'Warszawa',
        streetAddress: 'ul. Złota 44',
        zipcode: '00-120',
        distanceFilter: 1500,
        propertyType: 'Flat',
        typeOfBuilding: 'Apartment building',
        buildingMaterial: 'Concrete',
        heatingType: 'City heating',
        yearBuilt: 2019,
        floorArea: 82.5,
        floorLevel: 12,
        bedrooms: 3,
        bathrooms: 2,
        hasBalcony: true,
        hasElevator: true,
        hasSauna: false,
        hasParking: true,
        hasGym: true,
        hasAirConditioning: true,
        hasGarden: false,
        hasBasement: false,
        neighborhood: 'Śródmieście',
        distanceToPublicTransport: '180 m',
        hasHighways: false,
        boostProductivity: 'High',
        additionalFeatures: ['Concierge', 'City view'],
        valueEstimate: 1890000.0,
        currency: 'PLN',
        pricePerSqm: 22909.09,
        createdAt: '2026-03-10T10:30:00Z',
        updatedAt: '2026-03-11T08:15:00Z',
      ),
      ReportsListModel(
        id: 2,
        user: 1,
        country: 'Polska',
        state: 'Małopolskie',
        city: 'Kraków',
        streetAddress: 'ul. Rakowicka 15',
        zipcode: '31-511',
        distanceFilter: 1200,
        propertyType: 'Flat',
        typeOfBuilding: 'Tenement',
        buildingMaterial: 'Brick',
        heatingType: 'Gas',
        yearBuilt: 2016,
        floorArea: 64.0,
        floorLevel: 4,
        bedrooms: 2,
        bathrooms: 1,
        hasBalcony: true,
        hasElevator: true,
        hasSauna: false,
        hasParking: false,
        hasGym: false,
        hasAirConditioning: true,
        hasGarden: false,
        hasBasement: true,
        neighborhood: 'Stare Miasto',
        distanceToPublicTransport: '250 m',
        hasHighways: false,
        boostProductivity: 'Medium',
        additionalFeatures: ['Historic area', 'High ceilings'],
        valueEstimate: 1245000.0,
        currency: 'PLN',
        pricePerSqm: 19453.13,
        createdAt: '2026-02-20T13:00:00Z',
        updatedAt: '2026-02-21T09:45:00Z',
      ),
      ReportsListModel(
        id: 3,
        user: 1,
        country: 'Polska',
        state: 'Pomorskie',
        city: 'Gdańsk',
        streetAddress: 'ul. Nadmorska 7',
        zipcode: '80-506',
        distanceFilter: 2000,
        propertyType: 'House',
        typeOfBuilding: 'Villa',
        buildingMaterial: 'Brick',
        heatingType: 'Heat pump',
        yearBuilt: 2021,
        floorArea: 210.0,
        floorLevel: 0,
        bedrooms: 5,
        bathrooms: 3,
        hasBalcony: true,
        hasElevator: false,
        hasSauna: true,
        hasParking: true,
        hasGym: false,
        hasAirConditioning: true,
        hasGarden: true,
        hasBasement: false,
        neighborhood: 'Brzeźno',
        distanceToPublicTransport: '600 m',
        hasHighways: true,
        boostProductivity: 'High',
        additionalFeatures: ['Sea view', 'Large terrace'],
        valueEstimate: 3650000.0,
        currency: 'PLN',
        pricePerSqm: 17380.95,
        createdAt: '2026-01-05T09:20:00Z',
        updatedAt: '2026-01-05T09:20:00Z',
      ),
    ];
  }

  static List<PdfReportModel> getSamplePdfReports() {
    return [
      PdfReportModel(
        report: ReportData(
          id: 1,
          user: 1,
          streetAddress: 'ul. Złota 44',
          city: 'Warszawa',
          state: 'Mazowieckie',
          country: 'Polska',
          zipcode: '00-120',
          distanceFilter: 1500,
          lat: 52.23218,
          lon: 21.00291,
          propertyType: 'Flat',
          typeOfBuilding: 'Apartment building',
          buildingMaterial: 'Concrete',
          heatingType: 'City heating',
          yearBuilt: 2019,
          floorArea: 82.5,
          floorLevel: 12,
          bedrooms: 3,
          bathrooms: 2,
          hasBalcony: true,
          hasElevator: true,
          hasSauna: false,
          hasParking: true,
          hasGym: true,
          hasAirConditioning: true,
          hasGarden: false,
          hasBasement: false,
          valueEstimate: 1890000.0,
          currency: 'PLN',
          neighborhood: 'Śródmieście',
          distanceToPublicTransport: '180 m',
          hasHighways: false,
          boostProductivity: 'High',
          pricePerSqm: 22909.09,
          createdAt: '2026-03-10T10:30:00Z',
          updatedAt: '2026-03-11T08:15:00Z',
          sourceKind: 'manual',
          // governmentData: _warsawGovernmentData(),
        ),
        pricesInArea: PricesInArea(
          minPrice: 1620000.0,
          averagePrice: 1865000.0,
          maxPrice: 2210000.0,
          currency: 'PLN',
          sampleSize: 14,
        ),
        accuracyIndex: AccuracyIndex(
          percentage: 91.4,
          areaM2: 6.8,
          offersCount: 10,
          medianAreaDeltaPct: 0.071,
        ),
        rentalData: RentalData(
          rental: 9450.0,
          administrativeFees: 1323.0,
          estimatedRentalPrice: 113400.0,
          currency: 'PLN',
        ),
        location: LocationData(
          address: 'ul. Złota 44',
          fullAddress: 'ul. Złota 44, Warszawa, 00-120, Polska',
          city: 'Warszawa',
          state: 'Mazowieckie',
          country: 'Polska',
          zipcode: '00-120',
          neighborhood: 'Śródmieście',
          lat: 52.23218,
          lon: 21.00291,
        ),
        estimation: EstimationData(
          estimatedValue: 1890000.0,
          estimatedPricePerM2: 22909.09,
          lowValue: 1785000.0,
          highValue: 1985000.0,
          comparablesUsed: 10,
          confidence: 0.914,
          currency: 'PLN',
        ),
        comparable: const [
          ComparableProperty(
            id: 101,
            title: 'Luxury flat in city center',
            link: 'https://example.com/property/101',
            city: 'Warszawa',
            district: 'Śródmieście',
            street: 'ul. Złota 46',
            rooms: 3,
            bathrooms: 2,
            floor: 10,
            floorArea: 81.0,
            price: 1849000.0,
            pricePerM2: 22827.16,
            currency: 'PLN',
            similarityScore: 7.42,
            areaDeltaPct: 0.018,
            priceDeltaPct: 0.009,
          ),
          ComparableProperty(
            id: 102,
            title: 'Premium apartment with parking',
            link: 'https://example.com/property/102',
            city: 'Warszawa',
            district: 'Śródmieście',
            street: 'ul. Twarda 8',
            rooms: 3,
            bathrooms: 2,
            floor: 11,
            floorArea: 84.0,
            price: 1915000.0,
            pricePerM2: 22800.00,
            currency: 'PLN',
            similarityScore: 7.11,
            areaDeltaPct: 0.018,
            priceDeltaPct: 0.010,
          ),
        ],
        comparableCount: 2,
      ),
      PdfReportModel(
        report: ReportData(
          id: 2,
          user: 1,
          streetAddress: 'ul. Rakowicka 15',
          city: 'Kraków',
          state: 'Małopolskie',
          country: 'Polska',
          zipcode: '31-511',
          distanceFilter: 1200,
          lat: 50.06844,
          lon: 19.95485,
          propertyType: 'Flat',
          typeOfBuilding: 'Tenement',
          buildingMaterial: 'Brick',
          heatingType: 'Gas',
          yearBuilt: 2016,
          floorArea: 64.0,
          floorLevel: 4,
          bedrooms: 2,
          bathrooms: 1,
          hasBalcony: true,
          hasElevator: true,
          hasSauna: false,
          hasParking: false,
          hasGym: false,
          hasAirConditioning: true,
          hasGarden: false,
          hasBasement: true,
          valueEstimate: 1245000.0,
          currency: 'PLN',
          neighborhood: 'Stare Miasto',
          distanceToPublicTransport: '250 m',
          hasHighways: false,
          boostProductivity: 'Medium',
          pricePerSqm: 19453.13,
          createdAt: '2026-02-20T13:00:00Z',
          updatedAt: '2026-02-21T09:45:00Z',
          sourceKind: 'manual',
          // governmentData: _krakowGovernmentData(),
        ),
        pricesInArea: PricesInArea(
          minPrice: 1080000.0,
          averagePrice: 1210000.0,
          maxPrice: 1390000.0,
          currency: 'PLN',
          sampleSize: 9,
        ),
        accuracyIndex: AccuracyIndex(
          percentage: 87.8,
          areaM2: 5.2,
          offersCount: 8,
          medianAreaDeltaPct: 0.063,
        ),
        rentalData: RentalData(
          rental: 6200.0,
          administrativeFees: 868.0,
          estimatedRentalPrice: 74400.0,
          currency: 'PLN',
        ),
        location: LocationData(
          address: 'ul. Rakowicka 15',
          fullAddress: 'ul. Rakowicka 15, Kraków, 31-511, Polska',
          city: 'Kraków',
          state: 'Małopolskie',
          country: 'Polska',
          zipcode: '31-511',
          neighborhood: 'Stare Miasto',
          lat: 50.06844,
          lon: 19.95485,
        ),
        estimation: EstimationData(
          estimatedValue: 1245000.0,
          estimatedPricePerM2: 19453.13,
          lowValue: 1175000.0,
          highValue: 1315000.0,
          comparablesUsed: 8,
          confidence: 0.878,
          currency: 'PLN',
        ),
        comparable: const [
          ComparableProperty(
            id: 201,
            title: 'Renovated flat near center',
            link: 'https://example.com/property/201',
            city: 'Kraków',
            district: 'Stare Miasto',
            street: 'ul. Topolowa 18',
            rooms: 2,
            bathrooms: 1,
            floor: 3,
            floorArea: 63.0,
            price: 1219000.0,
            pricePerM2: 19349.21,
            currency: 'PLN',
            similarityScore: 6.88,
            areaDeltaPct: 0.016,
            priceDeltaPct: 0.012,
          ),
        ],
        comparableCount: 1,
      ),
      PdfReportModel(
        report: ReportData(
          id: 3,
          user: 1,
          streetAddress: 'ul. Nadmorska 7',
          city: 'Gdańsk',
          state: 'Pomorskie',
          country: 'Polska',
          zipcode: '80-506',
          distanceFilter: 2000,
          lat: 54.40612,
          lon: 18.64211,
          propertyType: 'House',
          typeOfBuilding: 'Villa',
          buildingMaterial: 'Brick',
          heatingType: 'Heat pump',
          yearBuilt: 2021,
          floorArea: 210.0,
          floorLevel: 0,
          bedrooms: 5,
          bathrooms: 3,
          hasBalcony: true,
          hasElevator: false,
          hasSauna: true,
          hasParking: true,
          hasGym: false,
          hasAirConditioning: true,
          hasGarden: true,
          hasBasement: false,
          valueEstimate: 3650000.0,
          currency: 'PLN',
          neighborhood: 'Brzeźno',
          distanceToPublicTransport: '600 m',
          hasHighways: true,
          boostProductivity: 'High',
          pricePerSqm: 17380.95,
          createdAt: '2026-01-05T09:20:00Z',
          updatedAt: '2026-01-05T09:20:00Z',
          sourceKind: 'manual',
          // governmentData: _gdanskGovernmentData(),
        ),
        pricesInArea: PricesInArea(
          minPrice: 3240000.0,
          averagePrice: 3560000.0,
          maxPrice: 4120000.0,
          currency: 'PLN',
          sampleSize: 7,
        ),
        accuracyIndex: AccuracyIndex(
          percentage: 89.9,
          areaM2: 11.4,
          offersCount: 7,
          medianAreaDeltaPct: 0.082,
        ),
        rentalData: RentalData(
          rental: 14200.0,
          administrativeFees: 1988.0,
          estimatedRentalPrice: 170400.0,
          currency: 'PLN',
        ),
        location: LocationData(
          address: 'ul. Nadmorska 7',
          fullAddress: 'ul. Nadmorska 7, Gdańsk, 80-506, Polska',
          city: 'Gdańsk',
          state: 'Pomorskie',
          country: 'Polska',
          zipcode: '80-506',
          neighborhood: 'Brzeźno',
          lat: 54.40612,
          lon: 18.64211,
        ),
        estimation: EstimationData(
          estimatedValue: 3650000.0,
          estimatedPricePerM2: 17380.95,
          lowValue: 3440000.0,
          highValue: 3825000.0,
          comparablesUsed: 7,
          confidence: 0.899,
          currency: 'PLN',
        ),
        comparable: const [
          ComparableProperty(
            id: 301,
            title: 'Modern seaside villa',
            link: 'https://example.com/property/301',
            city: 'Gdańsk',
            district: 'Brzeźno',
            street: 'ul. Morska 12',
            rooms: 5,
            bathrooms: 3,
            floor: 0,
            floorArea: 205.0,
            price: 3520000.0,
            pricePerM2: 17170.73,
            currency: 'PLN',
            similarityScore: 7.35,
            areaDeltaPct: 0.024,
            priceDeltaPct: 0.012,
          ),
          ComparableProperty(
            id: 302,
            title: 'Luxury house with garden',
            link: 'https://example.com/property/302',
            city: 'Gdańsk',
            district: 'Brzeźno',
            street: 'ul. Plażowa 5',
            rooms: 5,
            bathrooms: 3,
            floor: 0,
            floorArea: 218.0,
            price: 3715000.0,
            pricePerM2: 17041.28,
            currency: 'PLN',
            similarityScore: 7.08,
            areaDeltaPct: 0.038,
            priceDeltaPct: 0.019,
          ),
        ],
        comparableCount: 2,
      ),
    ];
  }

  static ReportGovernmentDataModel _warsawGovernmentData() {
    return ReportGovernmentDataModel(
      weatherSynopApi: const [
        ReportGovernmentWeatherPoint(
          station: 'Warszawa',
          stationId: 12375,
          pressure: 1012.4,
          precipitationSum: 0.0,
          temperature: 18.2,
          measurementDate: '2026-03-11',
          measurementHour: 8,
          windDirection: 210,
          windSpeed: 3.4,
          humidityRelative: 57.0,
        ),
      ],
      hydrologicalApi: const [
        ReportGovernmentHydrologyPoint(
          lat: 52.2394,
          lon: 21.0452,
          river: 'Wisła',
          station: 'Warszawa-Bulwary',
          stationId: 151180020,
          waterLevel: 244,
          waterTemperature: 9.6,
          voivodeship: 'mazowieckie',
        ),
      ],
      schoolsSmogApi: [
        ReportGovernmentSchoolSmogPoint(
          school: ReportGovernmentSchoolInfo(
            city: 'WARSZAWA',
            name: 'SZKOŁA PODSTAWOWA NR 75',
            street: 'UL. NIECAŁA 14',
            latitude: 52.2432,
            longitude: 21.0016,
            postCode: '00-098',
          ),
          data: ReportGovernmentSchoolSmogData(
            pm10Avg: 17.4,
            pm25Avg: 11.2,
            humidityAvg: 55.8,
            pressureAvg: 1011.7,
            temperatureAvg: 17.5,
          ),
          timestamp: DateTime.utc(2026, 3, 11, 8, 16),
        ),
        ReportGovernmentSchoolSmogPoint(
          school: ReportGovernmentSchoolInfo(
            city: 'WARSZAWA',
            name: 'TECHNIKUM ELEKTRONICZNE',
            street: 'UL. GEN. ZAJĄCZKA 7',
            latitude: 52.2544,
            longitude: 20.9829,
            postCode: '01-518',
          ),
          data: ReportGovernmentSchoolSmogData(
            pm10Avg: 20.9,
            pm25Avg: 13.4,
            humidityAvg: 58.1,
            pressureAvg: 1012.2,
            temperatureAvg: 16.8,
          ),
          timestamp: DateTime.utc(2026, 3, 11, 8, 16),
        ),
        ReportGovernmentSchoolSmogPoint(
          school: ReportGovernmentSchoolInfo(
            city: 'WARSZAWA',
            name: 'LICEUM OGÓLNOKSZTAŁCĄCE NR 5',
            street: 'UL. NOWOWIEJSKA 37A',
            latitude: 52.2226,
            longitude: 21.0128,
            postCode: '00-665',
          ),
          data: ReportGovernmentSchoolSmogData(
            pm10Avg: 16.1,
            pm25Avg: 10.6,
            humidityAvg: 56.4,
            pressureAvg: 1012.0,
            temperatureAvg: 18.1,
          ),
          timestamp: DateTime.utc(2026, 3, 11, 8, 16),
        ),
      ],
      hospitalsApi: const [
        {'name': 'Szpital Miejski', 'city': 'Warszawa'},
        {'name': 'Centralny Szpital Kliniczny', 'city': 'Warszawa'},
      ],
      asbestosWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl: 'https://esip.bazaazbestowa.gov.pl/geoserver/wfs/wms',
        statusCode: 200,
        contentType: 'text/xml;charset=UTF-8',
        checkedAt: DateTime.utc(2026, 3, 11, 8, 16),
      ),
      lotsWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl:
            'https://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?service=WMS&request=GetCapabilities',
        statusCode: 200,
        contentType: 'text/xml',
        checkedAt: DateTime.utc(2026, 3, 11, 8, 16),
      ),
      bdot10kWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl:
            'https://mapy.geoportal.gov.pl/wss/service/PZGIK/BDOT/WMS/PobieranieArkuszeMapBDOT10k?SERVICE=WMS&REQUEST=GetCapabilities',
        statusCode: 200,
        contentType: 'text/xml; charset=UTF-8',
        checkedAt: DateTime.utc(2026, 3, 11, 8, 16),
      ),
      airQualityData: ReportGovernmentAirQualityStatus(
        monitoringAqd: ReportGovernmentServiceStatus(
          serviceAvailable: true,
          serviceUrl:
              'https://inspire.gios.gov.pl/wss/monit-air-aqd/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities',
          statusCode: 200,
          contentType: 'text/xml',
          checkedAt: DateTime.utc(2026, 3, 11, 8, 16),
        ),
        monitoringChem: ReportGovernmentServiceStatus(
          serviceAvailable: true,
          serviceUrl:
              'https://inspire.gios.gov.pl/wss/monit-air-chem/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities',
          statusCode: 200,
          contentType: 'text/xml',
          checkedAt: DateTime.utc(2026, 3, 11, 8, 16),
        ),
      ),
      errors: const [],
      fetchedAt: DateTime.utc(2026, 3, 11, 8, 16),
      createdAt: DateTime.utc(2026, 3, 11, 8, 16),
      updatedAt: DateTime.utc(2026, 3, 11, 8, 16),
    );
  }

  static ReportGovernmentDataModel _krakowGovernmentData() {
    return ReportGovernmentDataModel(
      weatherSynopApi: const [
        ReportGovernmentWeatherPoint(
          station: 'Kraków',
          stationId: 12566,
          pressure: 1008.7,
          precipitationSum: 0.2,
          temperature: 14.6,
          measurementDate: '2026-02-21',
          measurementHour: 9,
          windDirection: 180,
          windSpeed: 2.2,
          humidityRelative: 68.3,
        ),
      ],
      hydrologicalApi: const [
        ReportGovernmentHydrologyPoint(
          lat: 50.0512,
          lon: 19.9369,
          river: 'Wisła',
          station: 'Kraków-Bielany',
          stationId: 152180030,
          waterLevel: 218,
          waterTemperature: 7.8,
          voivodeship: 'małopolskie',
        ),
      ],
      schoolsSmogApi:  [
        ReportGovernmentSchoolSmogPoint(
          school: ReportGovernmentSchoolInfo(
            city: 'KRAKÓW',
            name: 'SZKOŁA PODSTAWOWA NR 4',
            street: 'UL. SMOLEŃSK 5',
            latitude: 50.0598,
            longitude: 19.9291,
            postCode: '31-108',
          ),
          data: ReportGovernmentSchoolSmogData(
            pm10Avg: 28.3,
            pm25Avg: 19.6,
            humidityAvg: 63.2,
            pressureAvg: 1008.0,
            temperatureAvg: 13.7,
          ),
          timestamp: DateTime.utc(2026, 2, 21, 9, 46),
        ),
        ReportGovernmentSchoolSmogPoint(
          school: ReportGovernmentSchoolInfo(
            city: 'KRAKÓW',
            name: 'TECHNIKUM ŁĄCZNOŚCI',
            street: 'UL. MONTE CASSINO 31',
            latitude: 50.0447,
            longitude: 19.9202,
            postCode: '30-337',
          ),
          data: ReportGovernmentSchoolSmogData(
            pm10Avg: 31.1,
            pm25Avg: 21.8,
            humidityAvg: 65.4,
            pressureAvg: 1007.6,
            temperatureAvg: 12.9,
          ),
          timestamp:  DateTime.utc(2026, 2, 21, 9, 46),
        ),
      ],
      hospitalsApi: const [],
      asbestosWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl: 'https://esip.bazaazbestowa.gov.pl/geoserver/wfs/wms',
        statusCode: 200,
        contentType: 'text/xml;charset=UTF-8',
        checkedAt: DateTime.utc(2026, 2, 21, 9, 46),
      ),
      lotsWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl:
            'https://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?service=WMS&request=GetCapabilities',
        statusCode: 200,
        contentType: 'text/xml',
        checkedAt: DateTime.utc(2026, 2, 21, 9, 46),
      ),
      bdot10kWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl:
            'https://mapy.geoportal.gov.pl/wss/service/PZGIK/BDOT/WMS/PobieranieArkuszeMapBDOT10k?SERVICE=WMS&REQUEST=GetCapabilities',
        statusCode: 200,
        contentType: 'text/xml; charset=UTF-8',
        checkedAt: DateTime.utc(2026, 2, 21, 9, 46),
      ),
      airQualityData: ReportGovernmentAirQualityStatus(
        monitoringAqd: ReportGovernmentServiceStatus(
          serviceAvailable: true,
          serviceUrl:
              'https://inspire.gios.gov.pl/wss/monit-air-aqd/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities',
          statusCode: 200,
          contentType: 'text/xml',
          checkedAt: DateTime.utc(2026, 2, 21, 9, 46),
        ),
        monitoringChem: ReportGovernmentServiceStatus(
          serviceAvailable: false,
          serviceUrl:
              'https://inspire.gios.gov.pl/wss/monit-air-chem/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities',
          statusCode: 503,
          contentType: 'text/xml',
          checkedAt: DateTime.utc(2026, 2, 21, 9, 46),
        ),
      ),
      errors: const [
        {
          'hospitals_data': 'Temporary timeout while fetching hospitals dataset'
        },
      ],
      fetchedAt: DateTime.utc(2026, 2, 21, 9, 46),
      createdAt: DateTime.utc(2026, 2, 21, 9, 46),
      updatedAt: DateTime.utc(2026, 2, 21, 9, 46),
    );
  }

  static ReportGovernmentDataModel _gdanskGovernmentData() {
    return ReportGovernmentDataModel(
      weatherSynopApi: const [
        ReportGovernmentWeatherPoint(
          station: 'Gdańsk',
          stationId: 12195,
          pressure: 1015.1,
          precipitationSum: 0.0,
          temperature: 11.9,
          measurementDate: '2026-01-05',
          measurementHour: 9,
          windDirection: 320,
          windSpeed: 5.8,
          humidityRelative: 72.1,
        ),
      ],
      hydrologicalApi: const [
        ReportGovernmentHydrologyPoint(
          lat: 54.3611,
          lon: 18.6847,
          river: 'Martwa Wisła',
          station: 'Gdańsk-Port',
          stationId: 154180010,
          waterLevel: 508,
          waterTemperature: 5.4,
          voivodeship: 'pomorskie',
        ),
      ],
      schoolsSmogApi:  [
        ReportGovernmentSchoolSmogPoint(
          school: ReportGovernmentSchoolInfo(
            city: 'GDAŃSK',
            name: 'SZKOŁA PODSTAWOWA NR 20',
            street: 'UL. WRZESZCZAŃSKA 29',
            latitude: 54.3927,
            longitude: 18.6175,
            postCode: '80-409',
          ),
          data: ReportGovernmentSchoolSmogData(
            pm10Avg: 14.2,
            pm25Avg: 9.1,
            humidityAvg: 70.6,
            pressureAvg: 1014.6,
            temperatureAvg: 10.8,
          ),
          timestamp: DateTime.utc(2026, 1, 5, 9, 21),
        ),
        ReportGovernmentSchoolSmogPoint(
          school: ReportGovernmentSchoolInfo(
            city: 'GDAŃSK',
            name: 'TECHNIKUM NR 8',
            street: 'UL. CHŁODNA 6',
            latitude: 54.3845,
            longitude: 18.6541,
            postCode: '80-747',
          ),
          data: ReportGovernmentSchoolSmogData(
            pm10Avg: 12.8,
            pm25Avg: 8.7,
            humidityAvg: 73.4,
            pressureAvg: 1015.0,
            temperatureAvg: 11.2,
          ),
          timestamp: DateTime.utc(2026, 1, 5, 9, 21),
        ),
      ],
      hospitalsApi: const [
        {'name': 'Szpital św. Wojciecha', 'city': 'Gdańsk'},
      ],
      asbestosWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl: 'https://esip.bazaazbestowa.gov.pl/geoserver/wfs/wms',
        statusCode: 200,
        contentType: 'text/xml;charset=UTF-8',
        checkedAt: DateTime.utc(2026, 1, 5, 9, 21),
      ),
      lotsWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl:
            'https://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow?service=WMS&request=GetCapabilities',
        statusCode: 200,
        contentType: 'text/xml',
        checkedAt: DateTime.utc(2026, 1, 5, 9, 21),
      ),
      bdot10kWms: ReportGovernmentServiceStatus(
        serviceAvailable: true,
        serviceUrl:
            'https://mapy.geoportal.gov.pl/wss/service/PZGIK/BDOT/WMS/PobieranieArkuszeMapBDOT10k?SERVICE=WMS&REQUEST=GetCapabilities',
        statusCode: 200,
        contentType: 'text/xml; charset=UTF-8',
        checkedAt: DateTime.utc(2026, 1, 5, 9, 21),
      ),
      airQualityData: ReportGovernmentAirQualityStatus(
        monitoringAqd: ReportGovernmentServiceStatus(
          serviceAvailable: true,
          serviceUrl:
              'https://inspire.gios.gov.pl/wss/monit-air-aqd/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities',
          statusCode: 200,
          contentType: 'text/xml',
          checkedAt: DateTime.utc(2026, 1, 5, 9, 21),
        ),
        monitoringChem: ReportGovernmentServiceStatus(
          serviceAvailable: true,
          serviceUrl:
              'https://inspire.gios.gov.pl/wss/monit-air-chem/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities',
          statusCode: 200,
          contentType: 'text/xml',
          checkedAt: DateTime.utc(2026, 1, 5, 9, 21),
        ),
      ),
      errors: const [],
      fetchedAt: DateTime.utc(2026, 1, 5, 9, 21),
      createdAt: DateTime.utc(2026, 1, 5, 9, 21),
      updatedAt: DateTime.utc(2026, 1, 5, 9, 21),
    );
  }
}