# Generated by Django 5.1.6 on 2026-07-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budowa", "0002_budowa_lat_budowa_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="WpisDziennika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("data", models.DateField()),
                ("opis", models.TextField(blank=True)),
                ("uwagi", models.TextField(blank=True)),
                (
                    "pogoda",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slonecznie", "Słonecznie"),
                            ("czesciowe_zachmurzenie", "Częściowe zachmurzenie"),
                            ("pochmurno", "Pochmurno"),
                            ("deszcz", "Deszcz"),
                            ("burza", "Burza"),
                            ("snieg", "Śnieg"),
                            ("wiatr", "Silny wiatr"),
                            ("mgla", "Mgła"),
                            ("mroz", "Mróz"),
                        ],
                        max_length=30,
                    ),
                ),
                ("temperatura", models.FloatField(blank=True, null=True)),
                ("predkosc_wiatru", models.FloatField(blank=True, null=True)),
                ("opady", models.FloatField(blank=True, null=True)),
                ("pogoda_auto", models.BooleanField(default=False)),
                ("godziny_pracy", models.FloatField(default=0)),
                ("liczba_pracownikow", models.IntegerField(default=0)),
                ("autor_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wpisy_dziennika",
                        to="budowa.budowa",
                    ),
                ),
                (
                    "etap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wpisy_dziennika",
                        to="budowa.etapbudowy",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="ObecnoscNaBudowie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.IntegerField(blank=True, null=True)),
                ("imie_nazwisko", models.CharField(max_length=150)),
                ("rola", models.CharField(blank=True, max_length=100)),
                ("godziny", models.FloatField(default=8)),
                (
                    "wpis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obecnosci",
                        to="dziennik.wpisdziennika",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZdjecieDziennika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plik", models.ImageField(upload_to="dziennik/%Y/%m/")),
                ("opis", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wpis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zdjecia",
                        to="dziennik.wpisdziennika",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wpisdziennika",
            index=models.Index(
                fields=["company_id", "budowa", "data"],
                name="dziennik_wp_company_5d1d92_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wpisdziennika",
            unique_together={("budowa", "data")},
        ),
    ]
