# Generated by Django 5.1.6 on 2026-07-09 05:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("nazwa", models.CharField(max_length=255)),
                ("opis", models.TextField(blank=True)),
                ("jednostka", models.CharField(default="szt", max_length=20)),
                (
                    "kategoria",
                    models.CharField(
                        choices=[
                            ("beton", "Beton i kruszywa"),
                            ("stal", "Stal i metale"),
                            ("drewno", "Drewno i stolarka"),
                            ("ceramika", "Ceramika i bloki"),
                            ("izolacja", "Izolacja i hydroizolacja"),
                            ("instalacje", "Instalacje wod-kan"),
                            ("elektryka", "Elektryka"),
                            ("elewacja", "Elewacja i tynki"),
                            ("pokrycie", "Pokrycie dachowe"),
                            ("wykonczenie", "Wykończenie"),
                            ("chemia", "Chemia budowlana"),
                            ("narzedzia", "Narzędzia i sprzęt"),
                            ("inne", "Inne"),
                        ],
                        default="inne",
                        max_length=20,
                    ),
                ),
                ("producent", models.CharField(blank=True, max_length=100)),
                ("symbol", models.CharField(blank=True, max_length=100)),
                ("vat", models.PositiveSmallIntegerField(default=23)),
                (
                    "cena_netto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cena_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["kategoria", "nazwa"],
            },
        ),
        migrations.CreateModel(
            name="HistoriaCeny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cena_netto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data", models.DateField(default=django.utils.timezone.now)),
                (
                    "zrodlo",
                    models.CharField(
                        choices=[
                            ("reczne", "Ręczne"),
                            ("import", "Import CSV"),
                            ("kosztorys", "Z kosztorysu"),
                            ("zamowienie", "Z zamówienia"),
                        ],
                        default="reczne",
                        max_length=20,
                    ),
                ),
                ("uwagi", models.CharField(blank=True, max_length=255)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia_cen",
                        to="materialy.material",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="PozycjaZamowienia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("budowa_id", models.IntegerField(db_index=True)),
                ("kosztorys_id", models.IntegerField(blank=True, null=True)),
                ("etap_id", models.IntegerField(blank=True, null=True)),
                ("ilosc", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "ilosc_dostarczona",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "cena_netto_zakupu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("do_zamowienia", "Do zamówienia"),
                            ("zamowione", "Zamówione"),
                            ("w_dostawie", "W dostawie"),
                            ("dostarczone", "Dostarczone"),
                            ("zwrocone", "Zwrócone"),
                        ],
                        default="do_zamowienia",
                        max_length=20,
                    ),
                ),
                ("uwagi", models.CharField(blank=True, max_length=500)),
                ("data_potrzeby", models.DateField(blank=True, null=True)),
                ("data_zamowienia", models.DateField(blank=True, null=True)),
                ("data_dostawy", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pozycje",
                        to="materialy.material",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "data_potrzeby"],
            },
        ),
    ]
