# Generated by Django 5.1.6 on 2026-07-09 05:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                (
                    "budowa_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("kosztorys_id", models.IntegerField(blank=True, null=True)),
                ("numer", models.CharField(blank=True, max_length=50)),
                ("tytul", models.CharField(max_length=255)),
                ("klient_nazwa", models.CharField(max_length=255)),
                ("klient_adres", models.TextField(blank=True)),
                ("klient_nip", models.CharField(blank=True, max_length=30)),
                ("klient_email", models.EmailField(blank=True, max_length=254)),
                ("klient_telefon", models.CharField(blank=True, max_length=30)),
                ("wystawca_nazwa", models.CharField(blank=True, max_length=255)),
                ("wystawca_adres", models.TextField(blank=True)),
                ("wystawca_nip", models.CharField(blank=True, max_length=30)),
                ("wystawca_email", models.EmailField(blank=True, max_length=254)),
                ("wystawca_telefon", models.CharField(blank=True, max_length=30)),
                ("wstep", models.TextField(blank=True)),
                ("warunki", models.TextField(blank=True)),
                ("uwagi", models.TextField(blank=True)),
                ("pozycje", models.JSONField(default=list)),
                (
                    "wartosc_netto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("vat_procent", models.PositiveSmallIntegerField(default=23)),
                (
                    "wartosc_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "wartosc_brutto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "rabat_procent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "data_wystawienia",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("wazna_do", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("roboczy", "Roboczy"),
                            ("wyslana", "Wysłana"),
                            ("zaakceptowana", "Zaakceptowana"),
                            ("odrzucona", "Odrzucona"),
                            ("wygasla", "Wygasła"),
                        ],
                        default="roboczy",
                        max_length=20,
                    ),
                ),
                ("pdf_url", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.IntegerField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriaStatusuOferty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("roboczy", "Roboczy"),
                            ("wyslana", "Wysłana"),
                            ("zaakceptowana", "Zaakceptowana"),
                            ("odrzucona", "Odrzucona"),
                            ("wygasla", "Wygasła"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("uwagi", models.CharField(blank=True, max_length=500)),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia_statusu",
                        to="oferty.oferta",
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
    ]
